// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:level_up/data/local/models/combat_hive.dart';
import 'package:level_up/data/local/models/defi_hive.dart';
import 'package:level_up/data/local/models/message_hive.dart';
import 'package:level_up/data/local/models/rune_hive.dart';
import 'package:level_up/data/local/models/serie_combat_hive.dart';
import 'package:level_up/data/local/models/veilleur_hive.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CombatHiveAdapter());
    registerAdapter(DefiHiveAdapter());
    registerAdapter(MessageHiveAdapter());
    registerAdapter(RuneHiveAdapter());
    registerAdapter(SerieCombatHiveAdapter());
    registerAdapter(VeilleurHiveAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CombatHiveAdapter());
    registerAdapter(DefiHiveAdapter());
    registerAdapter(MessageHiveAdapter());
    registerAdapter(RuneHiveAdapter());
    registerAdapter(SerieCombatHiveAdapter());
    registerAdapter(VeilleurHiveAdapter());
  }
}
